# voidpen-frontend/nginx.conf
# 前台单独容器使用（SPA history 路由支持）
server {
    listen 80;
    root /usr/share/nginx/html/;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    gzip on;
    gzip_types text/html text/css application/javascript application/json;
}
