spring:
  profiles:
    active: dev
  application:
    name: voidpen-server
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies$LowerCamelCaseStrategy
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080

knife4j:
  enable: true
  setting:
    language: zh_cn

voidpen:
  jwt:
    secret: your-256-bit-secret-key-here-change-in-prod
    expire: 7200
